{{- if and .Values.backend.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
  labels:
    {{- include "employee-management-system.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-username: {{ .Values.postgresql.auth.username | b64enc | quote }}
{{- end }}