{{- if and .Values.backend.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-management-system.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "employee-management-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  postgres-username: {{ .Values.postgresql.auth.username | quote }}
{{- end }}