apiVersion: v1
kind: Secret
metadata:
  name: employee-management-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque

stringData:

  postgres-username: {{ .Values.postgresql.auth.username }}

  postgres-password: {{ .Values.postgresql.auth.password }}

  postgres-database: {{ .Values.postgresql.auth.database }}