spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:employee_qa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_[REDACTED_GENERIC_PASSWORD_2]}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: WARN
    com.employeesystem.emsbackend: INFO
  file:
    name: logs/ems-backend-qa.log
    max-size: 10MB
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
