spring.application.name=ems-backend

spring.datasource.url= jdbc:postgresql://localhost:5432/employee
spring.datasource.username=root
spring.datasource.password=Mysqlajith@143
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

#server.port=8082